name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  check-file:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.check_files.outputs.test }}
    steps:
      - name: Checkout
        #        uses: actions/checkout@master
        id: check_files
        run: echo "::set-output name=test::hello"
  sync-file:
    runs-on: ubuntu-latest
    needs: check-file
    if: needs.check-file.outputs.output1 == 'hello'
    steps:
      - name: test
        run:
        echo ${{needs.check-file.outputs.output1}}


