name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  check-file:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.Checkout.outputs.test }}
    steps:
      - name: Checkout
#        uses: actions/checkout@master
        run: echo "::set-output name=test::hello"


